spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  kafka:
    properties:
      security.protocol: PLAINTEXT
    bootstrap-servers: ${spring.embedded.kafka.brokers}
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"

tiltaksgjennomforing:
  altinn-varsel:
    uri: http://localhost:8091