spring:
  datasource:
    platform: postgres
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  kafka:
    consumer:
      properties:
        spring:
          json:
            value.default.type: no.nav.tag.tiltaksgjennomforing.varsel.kafka.SmsVarselMelding
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    banner-mode: "console"

tiltaksgjennomforing:
  topics:
    sms: sms
    sms-resultat: sms-resultat
  altinn-varsel:
    uri: http://localhost:8091