name: Bygg branch og opprett deployment-issue

on:
  push:
    branches:
      - '*'
      - '!master'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/tiltaksgjennomforing-varsel

jobs:
  bygg-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

#      - name: Oppsett Java 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#
#      - name: Gjenopprett Maven-cache
#        uses: actions/cache@v1
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Bygg og test med Maven
#        run: mvn package -B -Dsurefire.useFile=false

      - name: Sett variable
        run: |
          echo ::set-env name=TAG::"$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)"
          echo ::set-env name=IMAGE::"$IMAGE_BASE:$TAG"
          echo ::set-env name=BRANCH::"$(echo ${GITHUB_REF#refs/heads/})"
          echo $TAG
          echo $IMAGE
          echo $BRANCH

#      - name: Bygg, tag og push Docker-image
#        run: |
#          docker build --tag ${IMAGE} .
#          echo  ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
#          docker push ${IMAGE_BASE}

      - name: Opprett deployment-issue
        uses: actions/github-script@0.5.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Bygg av ${{ env.TAG }}',
              body: 'Kommenter med <b>/deploy ${{ env.TAG }}</b> for Ã¥ deploye til dev-fss.',
              labels: ['${{ env.BRANCH }}'],
              assignees: ['${{ github.actor }}']
            })